package common

const (
	// --- LANGKAH GLOBAL ---
	STEP_AWAL = 1 // Menggantikan 'CurrentStep: 1, AwaitingAnswer: false'

	// --- ALUR DATA DIRI (19 Langkah) ---
	STEP_DUSUN        = 1
	STEP_RT           = 2
	STEP_NAMA         = 3
	STEP_NO_KK        = 4
	STEP_NIK          = 5
	STEP_SEX          = 6
	STEP_TEMPAT_LAHIR = 7
	STEP_TANGGAL_LAHIR  = 8
	STEP_AGAMA        = 9
	STEP_PENDIDIKAN_KK = 10
	STEP_PENDIDIKAN_SEDANG = 11
	STEP_PEKERJAAN      = 12
	STEP_STATUS_KAWIN = 13
	STEP_KK_LEVEL     = 14
	STEP_WARGANEGARA  = 15
	STEP_NAMA_AYAH    = 16
	STEP_NAMA_IBU     = 17
	STEP_STATUS_DASAR = 18
	STEP_SUKU         = 19 // Checkpoint
	STEP_KONFIRMASI_DATA_DIRI = 20
	STEP_EDIT_DATA_DIRI       = 21

	STEP_CHECKPOINT_SUKU = 100
	STEP_NIK_DUPLIKATE    = 101

	STEP_MENU_DATA_DIRI = 200
	STEP_EDIT_CARI_NIK  = 201

	// --- ALUR PENGADUAN ---
	STEP_PENGADUAN_MENU         = 300
	STEP_PENGADUAN_WAITING      = 301
	STEP_PENGADUAN_CARI_ID      = 302
	STEP_PENGADUAN_VALIDASI_NIK = 303

	// --- ALUR SURAT ---
	STEP_SURAT_MENU_UTAMA       = 500
	STEP_SURAT_VALIDASI_NIK     = 501
	STEP_SURAT_PILIH_JENIS      = 502
	STEP_SURAT_INPUT_DATA       = 503
	STEP_SURAT_KONFIRMASI_FIELD = 504
	STEP_SURAT_CEK_PROGRES      = 505

	// --- ALUR ULASAN ---
	STEP_ULASAN_DATA_DIRI = 600
	STEP_ULASAN_SURAT     = 601
	STEP_ULASAN_PENGADUAN = 602
)
